# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MXWhere' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MXWhere
  pod 'ffmpeg-kit-macos-full', '~> 5.1'
  target 'MXWhereTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MXWhereUITests' do
    # Pods for testing
  end

end
